### PR TITLE
fix: hide the magnified img in zoom out mode

### PR DESCRIPTION
**Pull request by Ahmed-Basalib10**
Hi 👋 @Mario-Duarte 
I hope you are doing well!, I opened this PR  to solve **the issue with the images that don't have background**.

I use this package in my project and it is really nice, but recently I realised that there is an issue with the images that don't have a background, the issue is that in zoom out mode both images the original image and the magnified image are showing  at the same time and overlapping together.

- [before](https://ibb.co/vmPzw1M)
- [after](https://ibb.co/6bw4srg)

### CODE REVIEW

**Comment by Mario-Duarte** [comment]
Hi @Ahmed-Basalib10 Thanks for doing this, it may be an oversight while creating this as I never intended this to be used with images that had transparency such as `.png`.

But I appreciate you taking the time to add this to the main package

**Review by Mario-Duarte — CHANGES_REQUESTED** [review]
Could you please only create a pull request for the changes made to the `src/react-image-zoom.js`?

**Comment by Ahmed-Basalib10** [comment]
> Could you please only create a pull request for the changes made to the `src/react-image-zoom.js`?

Yes sure, it is done PR updated, now all the files are same as before just `src/react-image-zoom.js` changed. thanks

**Comment by Mario-Duarte** [comment]
> > Could you please only create a pull request for the changes made to the `src/react-image-zoom.js`?
> 
> Yes sure, it is done PR updated, now all the files are same as before just `src/react-image-zoom.js` changed. thanks

Thats great thank you, I will merge this and get a release out

**Review by Mario-Duarte — APPROVED** [review]

**Pull request merged**
